"""init

Revision ID: 0675c7511f6d
Revises:
Create Date: 2025-09-23 23:44:59.441231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0675c7511f6d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("FINANCE", "PERMANENT", name="item_type"), nullable=False
        ),
        sa.Column("exclusive", sa.Boolean(), nullable=False),
        sa.Column("energy_max_boost", sa.Float(), nullable=False),
        sa.Column("energy_recovery_boost", sa.Float(), nullable=False),
        sa.Column("energy_shild_boost", sa.Float(), nullable=False),
        sa.Column("image", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "tasks",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("DAELY", "WEAKLY", "QUEST", name="task_type"),
            nullable=False,
        ),
        sa.Column("reward", sa.Integer(), nullable=False),
        sa.Column(
            "reward_type", sa.Enum("MONEY", "EXP", name="reward_type"), nullable=False
        ),
        sa.Column("progress_max_points", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("energy", sa.SmallInteger(), nullable=False),
        sa.Column("experience", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "works",
        sa.Column("name", sa.String(length=2048), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("base_energy", sa.SmallInteger(), nullable=False),
        sa.Column("max_amount", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "item_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("item_name", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_name"],
            ["items.name"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "item_name", name="uix_item_user_user_item"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.String(length=2048), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("datetime_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("datetime_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "type",
            sa.Enum("BANK", "EVENT", "WORK", name="transaction_type"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("rewarded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_name"],
            ["tasks.name"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "task_name", name="uix_user_task_user_task"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tasks")
    op.drop_table("transactions")
    op.drop_table("item_user")
    op.drop_table("works")
    op.drop_table("users")
    op.drop_table("tasks")
    op.drop_table("items")
    # ### end Alembic commands ###
